[package]
name = "gfx_tutorial"
version = "0.1.0"
authors = ["georgeburton"]

[dependencies]
angular = { version = "0.1", git = "http://github.com/burtonageo/angular-rust" }
gfx = "0.14"
gfx_window_glutin = "0.14"
glutin = "0.7"
nalgebra = "0.10"
num = "0.1"
scopeguard = "0.3"
time = "0.1"
